### ISSUE TITLE
How do I change offsets 

### ISSUE THREAD

**Issue by Ry2n123** [xxlilx/cs2-external-bunnyhop#4]
How do I change the offsets?

**Comment by Ry2n123** [comment]
Nvm i found out i got it to work its amazing ty

**Comment by HashSilencer** [comment]
so how?

**Comment by Ry2n123** [comment]
Add me on discord I will do for you “ry2n_z1”
@HashSilencer

**Comment by HashSilencer** [comment]
do you reply yet?

**Comment by Ry2n123** [comment]
Sorry for late response I was sleeping I just sent everything you need to your discord

**Comment by granefb** [comment]
@Ry2n123 could you help me out as well? if you can I added you on discord my username is grain8949

**Comment by xxlilx** [comment]
https://github.com/xxlilx/cs2-external-bunnyhop/blob/main/README.md
